project:
  type: website
  output-dir: docs

website:
  title: "Lukas Sönning"
  site-url: https://lsoenning.github.io
  navbar:
    background: lightgrey
    foreground: black
    search: true
    left:
      - text: Home
        file: index.qmd
      - about.qmd
      - research.qmd
      - resources.qmd
      - posts.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

