project:
  type: website
  output-dir: docs

website:
  title: "Lukas Sönning"
  site-url: https://lsoenning.github.io
  navbar:
    background: lightgrey
    foreground: black
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Research
        file: research.qmd
      - text: Resources
        file: resources.qmd
      - text: Blog
        file: posts.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

