### Dr. Lukas Sönning

#### Short academic CV

- 2020 awarded PhD
- 2012-2022 Research and teaching assistant at the University of Bamberg
- 2006-2012 Studies in English, Geography and Pedagogy at the University of Bamberg


#### Awards

- 2014 Best poster award, Olinco conferenece, Olomouc ("Vowel reduction in German Learner English: Developmental patterns")
- 2018 Best paper by an early career researcher, ICAME39, Tampere (John Sinclair bursary) ("Visual inference for corpus linguistics")


#### Teaching

University courses

- Forming (new) words: The morphological architecture of English
- Applied data analysis for linguists
- Investigating Lerner English
- Second Language speech: Theory and practice
- Measuring (your) foreign accent: The acoustic analysis of non-native speech
- English phonetics & phonology
- English grammar analysis
- Translation English-German (intermediate and advanced level)
- Revision course for state exam candidates: Synchronic linguistics
- Revision course for state exam candidates: Translation English-German


Workshops

- 2023 (University of Würzburg) Analyzing language data using R and RStudio [slides part 1](resources_pages/test_multiplex.html){target="_blank"} | 
- 2019 (FJUEL conference, Bayreuth): Using "statistics" to learn about language: What matters (and what doesn‘t)
- 2019 (BICLCE conference, Bamberg): The replication crisis in science: Challenges and chances for linguistics
- 2018 (Uppsala) Statistical inference using estimation: Methods for corpus linguistics
- 2014 (EmMeth conference, Bamberg): Data visualization with R
- 2014 (FJUEL conference, Bamberg): Workshop on statistical methods
