### Research

#### Unpublished

- **Sönning**, Lukas. (to appear). (Re-)viewing the acquisition of rhythm in the light of L2 phonological theories. In Robert Fuchs (ed.), Speech rhythm in L2 and L3 varieties of English. Singapore: Springer.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/x36jh/) | `r icons::academicons$dataverse` [Data](https://doi.org/10.18710/GTI2BR) | `r icons::academicons$osf` [OSF](https://osf.io/25kq4) 

- **Sönning**, Lukas. (to appear). Drawing on principles of perception: The line plot. In Lukas Sönning & Ole Schützler (eds.) Data visualization in corpus linguistics: Reflections and future directions, VARIENG.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/tjfz5/) | `r icons::academicons$osf` [OSF](https://osf.io/ksr5a)

- **Sönning**, Lukas & Ole Schützler (eds.). (to appear). Data visualization in corpus linguistics: Reflections and future directions, VARIENG.

- **Sönning**, Lukas. (in review). Evaluation of text-level measures of lexical dispersion: Robustness and consistency.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/h9mvs/) | `r icons::academicons$dataverse` [Data](https://doi.org/10.18710/MNVB36) | `r icons::academicons$osf` [OSF](https://osf.io/rpfb8/) 

- **Sönning**, Lukas. (in review). Evaluation of keyness metrics: Reliability and interpretability.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/eb2n9/) | `r icons::academicons$dataverse` [Data](https://doi.org/10.18710/ATCQZW) | `r icons::academicons$osf` [OSF](https://osf.io/kcwus/)

- **Sönning**, Lukas. (in review). Count regression models for keyness analysis.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/25mwj/) | `r icons::academicons$osf` [OSF](https://osf.io/mc26t/)

- **Sönning**, Lukas & Jason Grafmiller. (in review). Seeing the wood for the trees: Predictive margins for random forests.   `r icons::academicons$psyarxiv` [Preprint](https://psyarxiv.com/jr8yk/) | [Data](https://osf.io/r4s87) | `r icons::academicons$osf` [OSF](https://osf.io/4tuv2)



\  

#### Published

Monograph

- **Sönning**, Lukas. 2020. *Phonological variation in German Learner English*. University of Bamberg dissertation. DOI: 10.20378/irb-49135   `r icons::academicons$'open-access'` [Open access](https://fis.uni-bamberg.de/bitstream/uniba/49135/3/fisba49135_A3a.pdf) | `r icons::academicons$dataverse` [Datasets](#data-diss) | `r icons::academicons$osf`  [OSF](https://osf.io/2pdh6/)

  
Edited volumes

- **Sönning**, Lukas & Valentin Werner. 2021. The replication crisis: Implications for linguistics. Special issue in *Linguistics*.   `r icons::academicons$'closed-access'` [Link](https://www.degruyter.com/journal/key/ling/59/5/html)  

- Christ, Hanna, Daniel Klenovšak, Lukas **Sönning** & Valentin Werner (eds.). 2016. *A blend of MaLT: Selected contributions from the Methods and Linguistic Theories Symposium*. Bamberg: University of Bamberg Press.   `r icons::academicons$'open-access'` [Open access](https://fis.uni-bamberg.de/bitstream/uniba/41360/1/BABEL15WernerMaLTopusse_A3a.pdf)


Journal articles

- **Sönning**, Lukas & Valentin Werner. 2021. The replication crisis, scientific revolutions, and linguistics. *Linguistics* 59(5), 1179-1206. DOI: 10.1515/ling-2019-0045   `r icons::academicons$'closed-access'` [Link](https://www.degruyter.com/document/doi/10.1515/ling-2019-0045/html?lang=de)  

- **Sönning**, Lukas. 2014. Unstressed vowels in German Learner English: An instrumental study. *Research in Language* 12(2), 163-173. DOI: 10.2478/rela-2014-0001   `r icons::academicons$'open-access'` [Open access](https://digijournals.uni.lodz.pl/rela/vol12/iss2/4/) | `r icons::academicons$osf` [OSF](https://osf.io/48ejg/)


Book chapters

- **Sönning**, Lukas & Manfred Krug. 2022. Comparing study designs and down-sampling strategies in corpus analysis: The importance of speaker metadata in the BNCs of 1994 and 2014. In Ole Schützler & Julia Schlüter (eds.), Data and methods in corpus linguistics: Comparative approaches, 127-159. Cambridge: Cambridge University Press. DOI: 10.1017/9781108589314.006   `r icons::academicons$'closed-access'` [Link](https://doi.org/10.1017/9781108589314.006) | `r icons::academicons$osf` [OSF](https://osf.io/v3byq/) | `r icons::academicons$dataverse` [Data](https://doi.org/10.18710/A3SATC)

- **Sönning**, Lukas & Julia Schlüter. 2022. Comparing standard reference corpora and Google Books Ngrams: Strengths, limitations and synergies in the contrastive study of variable h- in British and American English. In Ole Schützler & Julia Schlüter (eds.), Data and methods in corpus linguistics: Comparative approaches, 17-45. Cambridge: Cambridge University Press. DOI: 10.1017/9781108589314.002   `r icons::academicons$'closed-access'` [Link](https://doi.org/10.1017/9781108589314.002) | `r icons::academicons$osf` [OSF](https://osf.io/47p6u/)  

- Krug, Manfred & Lukas **Sönning**. 2018. Language change in Maltese English: The influence of age and parental languages. In: Patrizia Paggio & Albert Gatt (eds.), *The languages of Malta*, 247-270. Berlin: Language Science Press. DOI: 10.5281/zenodo.1181801   `r icons::academicons$'open-access'` [Open access](https://doi.org/10.5281/zenodo.1181801)


Proceedings

- **Sönning**, Lukas. 2016. The dot plot: A graphical tool for data analysis and presentation. In Hanna Christ, Daniel Klenovšak, Lukas Sönning & Valentin Werner (eds.), *A blend of MaLT: Selected contributions from the Methods and Linguistic Theories Symposium*, 101–129. Bamberg: University of Bamberg Press.   `r icons::academicons$'open-access'` [Open access](https://fis.uni-bamberg.de/bitstream/uniba/41360/1/BABEL15WernerMaLTopusse_A3a.pdf)  

- **Sönning**, Lukas. 2014. Developmental patterns in the reduction of unstressed vowels by German learners of English. In Ludmila Veselovská & Markéta Janebová (eds.), *Complex visibles out there: Proceedings of the Olomouc Linguistics Colloquium 2014: Language use and linguistic structure, vol. 4 Olomouc modern language series*, 765–778. Olomouc: Palacký University.   `r icons::academicons$'open-access'` [Open access](https://osf.io/kn4gp) | `r icons::academicons$osf` [OSF](https://osf.io/v5hrb/)

- **Sönning**, Lukas. 2013. Scrabble yourself to success: Methods in teaching transcription. In Joanna Przedlacka, John Maidment & Michael Ashby (eds.), *Proceedings of the Phonetics Teaching and Learning Conference, UCL, London, 8-10 August 2013*. London: Phonetics Teaching and Learning Conference, 87-90.  `r icons::academicons$'open-access'` [Open access](https://fis.uni-bamberg.de/bitstream/uniba/2422/2/fisba2422.pdf) | `r icons::academicons$osf` [OSF](https://osf.io/vxgmu/) | `r icons::academicons$dataverse` [Data](https://doi.org/10.18710/2UJHHU) 

\  

#### Datasets

- Sönning, Lukas. 2022. Speech rhythm in German Learner English: Dataset for "(Re-)viewing the acquisition of rhythm in the light of L2 phonological theories", https://doi.org/10.18710/GTI2BR, DataverseNO, V1.

- Sönning, Lukas & Manfred Krug. 2021. Actually in contemporary British speech: Data from the Spoken BNC corpora, https://doi.org/10.18710/A3SATC, DataverseNO, V1.

- Sönning, Lukas. 2022. Dataset for "Scrabble yourself to success: Methods in teaching transcription", https://doi.org/10.18710/2UJHHU, DataverseNO, V1.


####### Dissertation {#data-diss}

- Sönning, Lukas. 2021. The TRAP-DRESS contrast in German Learner English: Dataset for chapter 4 in "Phonological variation in German Learner English", https://doi.org/10.18710/ATIRRV, DataverseNO, V1.

- Sönning, Lukas. 2021. Clear vs. dark /l/ in German Learner English: Dataset for chapter 5 in "Phonological variation in German Learner English", https://doi.org/10.18710/G6PJ5F, DataverseNO, V1.

- Sönning, Lukas, Graham Pascoe, Isabel Rank and Christina Wunder. 2021. English /r/ in German Learner English: Dataset for chapter 6 in "Phonological variation in German Learner English", https://doi.org/10.18710/YDKDFG, DataverseNO, V1.

- Sönning, Lukas, Graham Pascoe, Isabel Rank and Christina Wunder. 2021. The labio-velar glide /w/ in German Learner English: Dataset for chapter 7 in "Phonological variation in German Learner English", https://doi.org/10.18710/F1A34O, DataverseNO, V1.

- Sönning, Lukas & Isabel Rank. 2021. The labiodental fricative /v/ in German Learner English: Dataset for chapter 8 in "Phonological variation in German Learner English", https://doi.org/10.18710/B276ZX, DataverseNO, V1.

- Sönning, Lukas, Graham Pascoe & Christina Wunder. 2021. The voiced dental fricative in German Learner English: Dataset for chapter 9 in "Phonological variation in German Learner English", https://doi.org/10.18710/DYAGZG, DataverseNO, V1.

- Sönning, Lukas & Graham Pascoe. 2021. Final voiced obstruents in German Learner English: Dataset for chapter 10 in "Phonological variation in German Learner English", https://doi.org/10.18710/DKIGE5, DataverseNO, V1.




